title: "Filip Hnízdo"
email: mail@filipnest.com
description: Filip's homepage.
url: "https://filipnest.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      image: "/images/meta.png"

exclude: [music_templates]

tag_page_layout: tag_page
tag_page_dir: tag

plugins:
- jekyll/tagging
- jekyll-seo-tag

permalink: :title
